#!/usr/bin/env bash
# This script takes a subdomain and a domain as input and provides information about the subdomain

printInformation () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  printInformation "$1" "www"
  printInformation "$1" "lb-01"
  printInformation "$1" "web-01"
  printInformation "$1" "web-02"
elif [ "$#" == 2 ]
then
  printInformation "$1" "$2"
fi
