#!/usr/bin/env bash
# This script displays information about subdomains of a given domain.

printInformation () {
    subdomain="$2"
    domain="$1"
    
    result=$(dig +short "$subdomain.$domain" A)

    if [ -n "$result" ]; then
        echo "The subdomain $subdomain is a A record and points to $result"
    else
        echo "The subdomain $subdomain does not have an A record"
    fi
}

if [ "$#" == 1 ]
then
  printInformation "$1" "www"
  printInformation "$1" "lb-01"
  printInformation "$1" "web-01"
  printInformation "$1" "web-02"
elif [ "$#" == 2 ]
then
  printInformation "$1" "$2"
fi
