#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to install nginx and print "Hello World"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx start
