#!/usr/bin/env bash
# Install nginx on your web-01 server
apt-get -y update
apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
sed -i "46i rewrite ^/redirect_me https://www.youtube.com/watch?v=NNoMwEGW_y4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/PageNotFound_404.html
sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
service nginx restart

