#!/usr/bin/env bash
#Configure HAproxy so that it send traffic to web-01 and web-02
sudo apt-get -y update
sudo apt-get -y install haproxy

# config file
server_config=\
"
frontend  opeyemi-frontend
        bind *:80
        mode http
        default_backend opeyemi-backend
backend opeyemi-backend
        balance roundrobin
        server 251675-web-01 3.85.136.193:80 check
        server 251675-web-02 107.22.144.21:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart

