#!/usr/bin/env bash                                                                                                                                       
# Bash script that configures a server to the below requirements                                                                                                                         
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs                                                                                                                   
cd /etc/nginx/sites-enabled/ || exit;                                                                                                                             
                                                                                                                           
rm default;                                                                                 
ln -s /etc/nginx/sites-available/default default;                                                                                                                           
sudo service nginx restart
