#!/usr/bin/env bash
# Configure Nginx to listen on port 80 and restart the service.
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
