#!/usr/bin/env bash
# Configure ufw so that it blocks all incoming traffic, except
# TCP ports:22 (SSH), 443 (HTTPS SSL), 80 (HTTP)

sudo apt update
sudo apt install ufw
sudo ufw enable
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw show added
sudo ufw enable
sudo ufw status
